#!/bin/bash
# ClipSave release script
# Usage: ./release.sh <version>
# Example: ./release.sh 2.8
#
# Prerequisites:
#   1. Apple Developer ID Application certificate installed (for codesigning)
#   2. Sparkle private key in Keychain (generated by generate_keys earlier)
#   3. xcrun notarytool credentials stored (see step 4 in README)

set -e

if [ -z "$1" ]; then
    echo "❌ Error: Provide a version number (e.g. ./release.sh 2.8)"
    exit 1
fi

VERSION="$1"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="${PROJECT_DIR}/build"
ARCHIVE_PATH="${BUILD_DIR}/ClipSave-${VERSION}.xcarchive"
EXPORT_PATH="${BUILD_DIR}/ClipSave-${VERSION}"
APP_PATH="${EXPORT_PATH}/ClipSave.app"
ZIP_PATH="${BUILD_DIR}/ClipSave-${VERSION}.zip"

echo "🏗  Building & archiving ClipSave V${VERSION}..."
mkdir -p "${BUILD_DIR}"
rm -rf "${ARCHIVE_PATH}" "${EXPORT_PATH}" "${ZIP_PATH}"

TEAM_ID="6U39FF46MG"

# 1. Archive
xcodebuild -project ClipSave.xcodeproj \
           -scheme ClipSave \
           -configuration Release \
           -archivePath "${ARCHIVE_PATH}" \
           -destination "generic/platform=macOS" \
           DEVELOPMENT_TEAM="${TEAM_ID}" \
           MARKETING_VERSION="${VERSION}" \
           CURRENT_PROJECT_VERSION="${VERSION}" \
           ENABLE_HARDENED_RUNTIME=YES \
           CODE_SIGN_INJECT_BASE_ENTITLEMENTS=NO \
           OTHER_CODE_SIGN_FLAGS="--timestamp --options=runtime" \
           archive

# 2. Export the .app
cat > "${BUILD_DIR}/exportOptions.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>developer-id</string>
    <key>signingStyle</key>
    <string>automatic</string>
    <key>teamID</key>
    <string>${TEAM_ID}</string>
</dict>
</plist>
EOF

xcodebuild -exportArchive \
           -archivePath "${ARCHIVE_PATH}" \
           -exportPath "${EXPORT_PATH}" \
           -exportOptionsPlist "${BUILD_DIR}/exportOptions.plist"

# 3. Zip the .app
echo "📦 Zipping ClipSave.app..."
cd "${EXPORT_PATH}"
ditto -c -k --sequesterRsrc --keepParent "ClipSave.app" "${ZIP_PATH}"
cd "${PROJECT_DIR}"

# 4. Notarize
echo "📨 Submitting to Apple for notarization..."
xcrun notarytool submit "${ZIP_PATH}" \
                       --keychain-profile "AC_PASSWORD" \
                       --wait

# 5. Staple the notarization to the app (and re-zip)
echo "🪪 Stapling notarization..."
xcrun stapler staple "${APP_PATH}"
cd "${EXPORT_PATH}"
rm "${ZIP_PATH}"
ditto -c -k --sequesterRsrc --keepParent "ClipSave.app" "${ZIP_PATH}"
cd "${PROJECT_DIR}"

# 6. Sign with Sparkle private key
echo "🔐 Signing with Sparkle key..."
SIGN_UPDATE=$(find ~/Library/Developer/Xcode/DerivedData -name "sign_update" -type f 2>/dev/null | head -1)
if [ -z "${SIGN_UPDATE}" ]; then
    echo "❌ Couldn't find sign_update tool. Open Xcode and let it resolve Sparkle, then try again."
    exit 1
fi

SIGNATURE_OUTPUT=$("${SIGN_UPDATE}" "${ZIP_PATH}")

echo ""
echo "✅ Release V${VERSION} ready!"
echo ""
echo "📁 Files:"
echo "   ${ZIP_PATH}"
echo ""
echo "📋 Add this to your appcast.xml inside <channel>:"
echo ""
echo "        <item>"
echo "            <title>Version ${VERSION}</title>"
echo "            <sparkle:version>${VERSION}</sparkle:version>"
echo "            <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>"
echo "            <sparkle:minimumSystemVersion>14.0</sparkle:minimumSystemVersion>"
echo "            <pubDate>$(date -R)</pubDate>"
echo "            <description><![CDATA["
echo "                <h3>What's new in V${VERSION}</h3>"
echo "                <ul><li>Describe changes here</li></ul>"
echo "            ]]></description>"
echo "            <enclosure"
echo "                url=\"https://github.com/Someshwar1108/ClipSave/releases/download/v${VERSION}/ClipSave-${VERSION}.zip\""
echo "                ${SIGNATURE_OUTPUT}"
echo "                type=\"application/octet-stream\" />"
echo "        </item>"
echo ""
echo "Next steps:"
echo "  1. Upload ${ZIP_PATH} to GitHub Releases (tag: v${VERSION})"
echo "  2. Paste the <item> block above into appcast.xml"
echo "  3. Commit & push appcast.xml"
echo "  4. Friends' apps auto-detect on next launch"
